matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.2-DEVELOPMENT-SNAPSHOT-2018-09-11-a
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.2-DEVELOPMENT-SNAPSHOT-2018-09-11-a

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
